# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../windows/mainWindow.ui',
# licensing of '../windows/mainWindow.ui' applies.
#
# Created: Tue Aug 14 12:15:54 2018
#      by: pyside2-uic  running on PySide2 5.11.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 695)
        font = QtGui.QFont()
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.999999)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color:#cccccc;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("background-color:#404040;font:#fcfcfc;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblActiveFont = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblActiveFont.setFont(font)
        self.lblActiveFont.setStyleSheet("color:#fcfcfc;")
        self.lblActiveFont.setObjectName("lblActiveFont")
        self.horizontalLayout.addWidget(self.lblActiveFont)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.chkObserve = QtWidgets.QCheckBox(self.frame)
        self.chkObserve.setStyleSheet("color:#fcfcfc;")
        self.chkObserve.setObjectName("chkObserve")
        self.horizontalLayout.addWidget(self.chkObserve)
        self.btnPdbExport = QtWidgets.QPushButton(self.frame)
        self.btnPdbExport.setStyleSheet("color:#ff0000;")
        self.btnPdbExport.setObjectName("btnPdbExport")
        self.horizontalLayout.addWidget(self.btnPdbExport)
        self.sldTrans = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldTrans.sizePolicy().hasHeightForWidth())
        self.sldTrans.setSizePolicy(sizePolicy)
        self.sldTrans.setMinimum(40)
        self.sldTrans.setMaximum(100)
        self.sldTrans.setSingleStep(1)
        self.sldTrans.setProperty("value", 100)
        self.sldTrans.setOrientation(QtCore.Qt.Horizontal)
        self.sldTrans.setObjectName("sldTrans")
        self.horizontalLayout.addWidget(self.sldTrans)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lblFontSize = QtWidgets.QLabel(self.frame)
        self.lblFontSize.setStyleSheet("color:#fcfcfc;")
        self.lblFontSize.setObjectName("lblFontSize")
        self.horizontalLayout.addWidget(self.lblFontSize)
        self.cmbFontSize = QtWidgets.QComboBox(self.frame)
        self.cmbFontSize.setMinimumSize(QtCore.QSize(60, 0))
        self.cmbFontSize.setStyleSheet("color:#fcfcfc;")
        self.cmbFontSize.setObjectName("cmbFontSize")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.horizontalLayout.addWidget(self.cmbFontSize)
        self.cmbTextSamples = QtWidgets.QComboBox(self.frame)
        self.cmbTextSamples.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbTextSamples.setStyleSheet("color:#fcfcfc;")
        self.cmbTextSamples.setObjectName("cmbTextSamples")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.horizontalLayout.addWidget(self.cmbTextSamples)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.textEdit.setFont(font)
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setStyleSheet("background:#ffffff;")
        self.textEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Iraq))
        self.textEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon1)
        self.actionSettings.setObjectName("actionSettings")
        self.actionTo_PDF = QtWidgets.QAction(MainWindow)
        self.actionTo_PDF.setObjectName("actionTo_PDF")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Typo Viewer", None, -1))
        self.lblActiveFont.setText(QtWidgets.QApplication.translate("MainWindow", "Default Font", None, -1))
        self.chkObserve.setText(QtWidgets.QApplication.translate("MainWindow", "Observe", None, -1))
        self.btnPdbExport.setText(QtWidgets.QApplication.translate("MainWindow", "PDF", None, -1))
        self.lblFontSize.setText(QtWidgets.QApplication.translate("MainWindow", "Size: ", None, -1))
        self.cmbFontSize.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.cmbFontSize.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.cmbFontSize.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "12", None, -1))
        self.cmbFontSize.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "18", None, -1))
        self.cmbFontSize.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "36", None, -1))
        self.cmbFontSize.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "48", None, -1))
        self.cmbFontSize.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "64", None, -1))
        self.cmbFontSize.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "72", None, -1))
        self.cmbFontSize.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "96", None, -1))
        self.cmbFontSize.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "144", None, -1))
        self.cmbFontSize.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "180", None, -1))
        self.cmbFontSize.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "220", None, -1))
        self.cmbFontSize.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "250", None, -1))
        self.cmbTextSamples.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "custom text..", None, -1))
        self.cmbTextSamples.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "arabic_1", None, -1))
        self.cmbTextSamples.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "arabic_2", None, -1))
        self.cmbTextSamples.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "kurdish", None, -1))
        self.cmbTextSamples.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "marks", None, -1))
        self.cmbTextSamples.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "persian_arabic", None, -1))
        self.cmbTextSamples.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "persian_arabic2", None, -1))
        self.cmbTextSamples.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "Quran", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.actionTo_PDF.setText(QtWidgets.QApplication.translate("MainWindow", "To PDF", None, -1))
        self.actionTo_PDF.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Export as PDF Document", None, -1))

import TypoViewer.resources.icons_db
import TypoViewer.resources.samples
