# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../windows/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 695)
        font = QtGui.QFont()
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.999999)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color:#cccccc;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("background-color:#404040;font:#fcfcfc;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblActiveFont = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblActiveFont.setFont(font)
        self.lblActiveFont.setStyleSheet("color:#fcfcfc;")
        self.lblActiveFont.setObjectName("lblActiveFont")
        self.horizontalLayout.addWidget(self.lblActiveFont)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.chkObserve = QtWidgets.QCheckBox(self.frame)
        self.chkObserve.setStyleSheet("color:#fcfcfc;")
        self.chkObserve.setObjectName("chkObserve")
        self.horizontalLayout.addWidget(self.chkObserve)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lblFontSize = QtWidgets.QLabel(self.frame)
        self.lblFontSize.setStyleSheet("color:#fcfcfc;")
        self.lblFontSize.setObjectName("lblFontSize")
        self.horizontalLayout.addWidget(self.lblFontSize)
        self.cmbFontSize = QtWidgets.QComboBox(self.frame)
        self.cmbFontSize.setStyleSheet("color:#fcfcfc;")
        self.cmbFontSize.setObjectName("cmbFontSize")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.cmbFontSize.addItem("")
        self.horizontalLayout.addWidget(self.cmbFontSize)
        self.sldFontSize = QtWidgets.QSlider(self.frame)
        self.sldFontSize.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldFontSize.sizePolicy().hasHeightForWidth())
        self.sldFontSize.setSizePolicy(sizePolicy)
        self.sldFontSize.setMinimumSize(QtCore.QSize(160, 0))
        self.sldFontSize.setStyleSheet("color:#fcfcfc;")
        self.sldFontSize.setOrientation(QtCore.Qt.Horizontal)
        self.sldFontSize.setObjectName("sldFontSize")
        self.horizontalLayout.addWidget(self.sldFontSize)
        self.cmbTextSamples = QtWidgets.QComboBox(self.frame)
        self.cmbTextSamples.setStyleSheet("color:#fcfcfc;")
        self.cmbTextSamples.setObjectName("cmbTextSamples")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.cmbTextSamples.addItem("")
        self.horizontalLayout.addWidget(self.cmbTextSamples)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.textEdit.setFont(font)
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setStyleSheet("background:#ffffff;")
        self.textEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Iraq))
        self.textEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon1)
        self.actionSettings.setObjectName("actionSettings")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Typo Viewer"))
        self.lblActiveFont.setText(_translate("MainWindow", "Default Font"))
        self.chkObserve.setText(_translate("MainWindow", "Observe"))
        self.lblFontSize.setText(_translate("MainWindow", "Size: "))
        self.cmbFontSize.setItemText(0, _translate("MainWindow", "8"))
        self.cmbFontSize.setItemText(1, _translate("MainWindow", "9"))
        self.cmbFontSize.setItemText(2, _translate("MainWindow", "10"))
        self.cmbFontSize.setItemText(3, _translate("MainWindow", "12"))
        self.cmbFontSize.setItemText(4, _translate("MainWindow", "14"))
        self.cmbFontSize.setItemText(5, _translate("MainWindow", "18"))
        self.cmbFontSize.setItemText(6, _translate("MainWindow", "24"))
        self.cmbFontSize.setItemText(7, _translate("MainWindow", "36"))
        self.cmbFontSize.setItemText(8, _translate("MainWindow", "48"))
        self.cmbFontSize.setItemText(9, _translate("MainWindow", "64"))
        self.cmbFontSize.setItemText(10, _translate("MainWindow", "72"))
        self.cmbFontSize.setItemText(11, _translate("MainWindow", "96"))
        self.cmbFontSize.setItemText(12, _translate("MainWindow", "144"))
        self.cmbFontSize.setItemText(13, _translate("MainWindow", "288"))
        self.cmbTextSamples.setItemText(0, _translate("MainWindow", "custom text.."))
        self.cmbTextSamples.setItemText(1, _translate("MainWindow", "arabic_1"))
        self.cmbTextSamples.setItemText(2, _translate("MainWindow", "arabic_2"))
        self.cmbTextSamples.setItemText(3, _translate("MainWindow", "kurdish"))
        self.cmbTextSamples.setItemText(4, _translate("MainWindow", "marks"))
        self.cmbTextSamples.setItemText(5, _translate("MainWindow", "persian_arabic"))
        self.cmbTextSamples.setItemText(6, _translate("MainWindow", "persian_arabic2"))
        self.cmbTextSamples.setItemText(7, _translate("MainWindow", "Quran"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))

import TypoViewer.resources.icons_db
import TypoViewer.resources.samples
